[project]
name = "main"
version = "1.0.0"
requires-python = ">= 3.12"
dependencies = [
    "infisicalsdk >=0.2.0",
    "dagger-io",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
dagger-io = { path = "./sdk", editable = true }
